[palettes.list.catppuccin]
hue-black = '#1E1E2E'
hue-grey = '#6C7086'
hue-blue = '#89B4FA'
hue-green = '#A6E3A1'
hue-orange = '#FAB387'
hue-red = '#F38BA8'
hue-white = '#CDD6F4'
hue-yellow = '#F9E2AF'
hue-accent = '#CBA6F7'

secondary-prompt-foreground = 'p:hue-black'
secondary-prompt-background = 'p:hue-yellow'
transient-prompt-foreground = 'p:hue-black'
transient-prompt-background = 'p:hue-grey'

session-foreground = 'p:hue-black'
session-background = 'p:hue-yellow'

sysinfo-foreground = 'p:hue-white'
sysinfo-background = 'p:hue-accent'

path-foreground = 'p:hue-white'
path-background = 'p:hue-orange'

git-foreground = 'p:hue-black'
git-background = 'p:hue-green'
git-foreground-diverged = 'p:hue-white'
git-background-dirty = 'p:hue-yellow'
git-background-diverged = 'p:hue-red'
git-background-ahead = '#49416D'
git-background-behind = '#7A306C'

root-foreground = 'p:hue-white'
root-background = 'p:hue-yellow'

python-foreground = '#ffd43b'
python-background = '#306998'

prompt-foreground = 'p:hue-blue'
prompt-foreground-error = 'p:hue-red'

duration-foreground = 'p:hue-yellow'
time-foreground = 'p:hue-blue'
separator-foreground = 'p:hue-white'
